# Generated by Django 4.2 on 2023-04-11 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_delete_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Delete_post',
        ),
    ]
